version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/core/__tests__/fixtures/next
    schedule:
      interval: daily
      time: "14:00"
      timezone: America/Boise
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - compat
    allow:
      - dependency-name: next
      - dependency-name: react
      - dependency-name: react-dom
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
    groups:
      next-stack:
        patterns:
          - next
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: npm
    directory: /packages/core/__tests__/fixtures/vite
    schedule:
      interval: daily
      time: "14:00"
      timezone: America/Boise
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - compat
    allow:
      - dependency-name: react
      - dependency-name: react-dom
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
    groups:
      react-stack:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
