/* AUTO-GENERATED - DO NOT EDIT */
export const bodyAttributes = {
  "data-blur-global": "0px",
  "data-child": "closed",
  "data-number": "1",
  "data-test-color": "red",
  "data-test-opacity": "1",
  "data-test-size": "md",
  "data-test-spacing": "8px",
  "data-test-ssr-theme": "light",
  "data-test-theme": "light",
  "data-test-toggle": "off",
  "data-theme": "light",
  "data-theme-2": "light",
  "data-theme-ssr": "light",
  "data-theme-three": "light",
  "data-toggle-boolean": "true",
  "data-toggle-function": "white",
  "data-use-effect-theme": "light"
};
export const variantKeyMap = {
  "data-blur": true,
  "data-blur-global": true,
  "data-child": true,
  "data-dialog": true,
  "data-faq": true,
  "data-mobile": true,
  "data-number": true,
  "data-scope": true,
  "data-test-accordion": true,
  "data-test-color": true,
  "data-test-opacity": true,
  "data-test-size": true,
  "data-test-spacing": true,
  "data-test-ssr-menu": true,
  "data-test-ssr-theme": true,
  "data-test-tab": true,
  "data-test-theme": true,
  "data-test-toggle": true,
  "data-theme": true,
  "data-theme-2": true,
  "data-theme-ssr": true,
  "data-theme-three": true,
  "data-toggle-boolean": true,
  "data-toggle-function": true,
  "data-use-effect-theme": true
};
